# This is a sample aws-auth-patch.yml file. 
# Actual aws-auth-patch.yml will be created at /System/Volumes/Data/private/tmp/aws-auth-patch.yml path.

apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::695464577385:role/UdacityFlaskDeployCBKubectlRole
      username: build
      groups:
        - system:masters
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::695464577385:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-J3AWYQKNKW2I
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-07-09T09:52:35Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "13183"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 32aaae53-6e64-4daf-90ae-9fd05ec72af0
